# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

test:
  adapter: postgresql
  encoding: unicode
  database: event_management_test
  pool: 5
  username: ogryzek
  password: 
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: event_management_development
  pool: 5
  username: ogryzek
  password:  
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: event_management_production
  pool: 5
  username: ogryzek
  password: 
  timeout: 5000