1:
  name: "Salman Alam"
  linkedin: "http://www.linkedin.com/profile/view?id=316501614&trk=nav_responsive_tab_profile_pic"
  github: "https://github.com/ogryzek"
  twitter: "http://www.twitter.com/drew_bro"

3:
  name: "Abrar Musa"
  linkedin: "http://www.linkedin.com/profile/view?id=316501614&trk=nav_responsive_tab_profile_pic"
  github: "https://github.com/ogryzek"
  twitter: "http://www.twitter.com/drew_bro"

3:
  name: "Jef Curtis"
  image: "https://dl.dropboxusercontent.com/u/525680/2013-12-14%2021.31.59.jpg"
  linkedin: "http://www.linkedin.com/profile/view?id=316499239&trk=nav_responsive_tab_profile"
  github: "https://github.com/JefCurtis"
  twitter: "http://www.twitter.com/jefcurtis"

4:
  name: "Drew Ogryzek"
  image: "https://lh5.googleusercontent.com/-Q5KW5u0k_jw/UgBAzjf9kiI/AAAAAAAAAO8/lLRdbGuy6tM/s612-no/DrewGrey.png"
  linkedin: "http://www.linkedin.com/profile/view?id=316501614&trk=nav_responsive_tab_profile_pic"
  github: "https://github.com/ogryzek"
  twitter: "http://www.twitter.com/drew_bro"

5:
  name: "Arash Ouji"
  linkedin: "http://www.linkedin.com/profile/view?id=316501614&trk=nav_responsive_tab_profile_pic"
  github: "https://github.com/ogryzek"
  twitter: "http://www.twitter.com/drew_bro"

6:
  name: "Brandon Ricci"
  image: "http://m.c.lnkd.licdn.com/media/p/1/000/243/22d/2eb5a28.jpg"
  linkedin: "http://www.linkedin.com/profile/view?id=248163787&goback=%2Enmp_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1&trk=spm_pic"
  github: "https://github.com/brandontricci"

7:
  name: "Kelly Waters"
  linkedin: "http://www.linkedin.com/profile/view?id=316501614&trk=nav_responsive_tab_profile_pic"
  github: "https://github.com/ogryzek"
  twitter: "http://www.twitter.com/drew_bro"

8:
  name: "Don Brew"
  linkedin: "http://www.linkedin.com/profile/view?id=316501614&trk=nav_responsive_tab_profile_pic"
  github: "https://github.com/ogryzek"
  twitter: "http://www.twitter.com/drew_bro"
