1:
  name: "Salman Alam"
  linkedin: "http://www.linkedin.com/profile/view?id=110484888&authType=NAME_SEARCH&authToken=W4M9&locale=en_US&srchid=2481637871392055865845&srchindex=1&srchtotal=50&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A2481637871392055865845%2CVSRPtargetId%3A110484888%2CVSRPcmpt%3Aprimary"
  github: "https://github.com/salmanprk"
  twitter: "http://www.twitter.com/drew_bro"

3:
  name: "Abrar Musa"
  image: "https://1.gravatar.com/avatar/49be1c933f15a9e7b96c6dd7f989eddd?d=https%3A%2F%2Fidenticons.github.com%2F0169f0d2f7c88863e7dfe9ba64a15213.png&r=x&s=400"
  linkedin: "http://www.linkedin.com/profile/view?id=145789888&locale=en_US&trk=tyah2&trkInfo=tas%3AAbrar%20Musa%2Cidx%3A1-1-1"
  github: "https://github.com/abrarmusa"
  twitter: "http://www.twitter.com/drew_bro"

4:
  name: "Drew Ogryzek"
  image: "https://lh5.googleusercontent.com/-Q5KW5u0k_jw/UgBAzjf9kiI/AAAAAAAAAO8/lLRdbGuy6tM/s612-no/DrewGrey.png"
  linkedin: "http://www.linkedin.com/profile/view?id=316501614&trk=nav_responsive_tab_profile_pic"
  github: "https://github.com/ogryzek"
  twitter: "http://www.twitter.com/drew_bro"

5:
  name: "Arash Ouji"
  linkedin: "http://www.linkedin.com/profile/view?id=187414180"
  github: "https://github.com/aouji"
  twitter: ""

6:
  name: "Brandon Ricci"
  linkedin: "http://www.linkedin.com/profile/view?id=316501614&trk=nav_responsive_tab_profile_pic"
  github: "https://github.com/ogryzek"
  twitter: "http://www.twitter.com/drew_bro"

7:
  name: "Kelly Waters"
  image: "http://m.c.lnkd.licdn.com/media/p/5/000/23d/169/16ef873.jpg"
  linkedin: "http://www.linkedin.com/profile/view?id=46306336&locale=en_US&trk=tyah&trkInfo=tas%3Ake%2Cidx%3A2-4-5"
  github: "https://github.com/kwaters12"
  twitter: "http://www.twitter.com/kellyminjaro"

8:
  name: "Don Wong"
  image: "https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-frc3/t31/1890466_10150360844189981_70242708_o.jpg"
  linkedin: "http://www.linkedin.com/pub/d-wong/36/213/173"
  github: "https://github.com/donwon"
  twitter: "#"


9: 
  name: "Jef Curtis"
  image: "https://dl.dropboxusercontent.com/u/525680/2013-12-14%2021.31.59.jpg"
  linkedin: "http://www.linkedin.com/profile/view?id=316499239&trk=nav_responsive_tab_profile"
  github: "https://github.com/JefCurtis"
  twitter: "http://www.twitter.com/jefcurtis"

